config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :users, only: [:new, :create, :show]
  resources :events, except: [:edit, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :attendances
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: :creator_id, class_name: "Event"
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances

  def previous_events
    self.attended_events.where("date < ?", Time.now)
  end

  def upcoming_events
    self.attended_events.where("date > ?", Time.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  def current_user
    User.find_by(id: session[:user_id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = current_user.created_events
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      current_user.attended_events << @event
      redirect_to @event
    else
      render :new
    end

  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :creator_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:session][:name])
    if !user.nil?
      log_in user
      redirect_to user
    else
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def log_out
    session[:user_id] = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<section class="section">
  <div class="container">
    <div class="column is-left is-one-third">
      <h1>Previous Events</h1>
      <% current_user.previous_events.each do |event| %>
        <ul>
          <li><%= link_to event.title, event %></li>
          <li><%= event.description %></li>
          <li><%= event.date %></li><br>
        </ul>
      <% end %>
      <br><br>
      <h1>Upcoming Events</h1>
      <% current_user.upcoming_events.each do |event| %>
        <ul>
          <li><%= link_to event.title, event %></li>
          <li><%= event.description %></li>
          <li><%= event.date %></li><br>
        </ul>
      <% end %>

      <%= link_to "Create a New Event", new_event_path %>

      <%= link_to "Back to your page", user_path(current_user) %>

    </div>
  </div>
</section>

app/views/events/new.html.erb
<section class="section">
  <div class="container">
    <div class="column is-centered">
      <div class="column is-4">
        <h1>Create an Event</h1>
        <%= form_for @event do |f| %>
          <% if @event.errors.any? %>
            <% @event.errors.full_messages.each do |msg| %>
              <ul>
                <li><%= msg %></li>
              </ul>
            <% end %>
          <% end %>
          <p>
            <%= f.label :title, "Event name:" %><br>
            <%= f.text_field :title %>
          </p>
          <p>
            <%= f.label :description, "Event Description:" %><br>
            <%= f.text_area :description %>
          </p>
          <p>
            <%= f.label :date, "Event Date:" %><br>
            <%= f.date_field :date %>
          </p>
          <p>
            <%= f.submit %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/events/show.html.erb
<p>

  Event Name: <%= @event.title %>

</p>

<p>

  Event Description: <%= @event.description %>

</p>

<p>

  Event Date: <%= @event.date %>

</p>

<p>

  Created by: <%= @event.creator.name %>

</p>

<p>

  Attended by:
  <% @event.attendees.each do |attendee| %>
    <%= attendee.name %>
  <% end %>

</p>

<%= link_to "See All of Your Events", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>

      <a class="navbar-item">
        Documentation
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if !current_user %>
            <%= link_to "Sign up", new_user_path, class: "button is-primary" %>
            <%= link_to "Login", new_session_path, class: "button is-light" %>
          <% else %>
            <%= link_to "Sign Out", destroy_session_path, method: :delete, class: "button is-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<section class="section new-user">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <h1 class="title is-2">Sign In</h1>
        <%= form_for @user do |f| %>
          <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |msg| %>
              <ul>
                <li><%= msg %></li>
              </ul>
            <% end %>
          <% end %>
          <div class="field">
            <div class="control">
              <%= f.label :name, "Username:" %><br>
              <%= f.text_field :name %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= f.label :email, "Email:" %><br>
              <%= f.text_field :email %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= f.submit "Sign Up", class: "button is-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<aside>
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        Sign Up Here
      </div>
    </div>
  </div>
</aside>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="column is-center is-one-third">
      <p><%= current_user.name %></p>

      <% @user.created_events.each do |event| %>
        <ul>
          <li><%= link_to event.title, event_path %></li>
        </ul>
      <% end %>

    </div>
    <%= link_to "Create a New Event", new_event_path %>
  </div>
  <%= link_to "Log Out", session_path, method: :delete %>
</section>